version: "3"
services:
  app:
      image: node:lts-alpine
      container_name: carenbooker
      restart: always
      volumes:
        - /etc/timezone:/etc/timezone:ro
        - ./:/app
      working_dir: /app
      environment:
        NODE_ENV: development
        TZ: "Europe/Oslo"
      ports:
        - 14151:3000
      command: sh -c "npm i && npm run build && npm run serve"
